# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1166, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pdf_tab_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.pdf_tab_3.setGeometry(QtCore.QRect(10, 10, 1151, 591))
        self.pdf_tab_3.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.pdf_tab_3.setObjectName("pdf_tab_3")
        self.extract_tab = QtWidgets.QWidget()
        self.extract_tab.setObjectName("extract_tab")
        self.pdf_tab_3.addTab(self.extract_tab, "")
        self.pdf_tab = QtWidgets.QWidget()
        self.pdf_tab.setObjectName("pdf_tab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.pdf_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 80, 1131, 471))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.guides_table = QtWidgets.QTableView(self.verticalLayoutWidget_3)
        self.guides_table.setObjectName("guides_table")
        self.verticalLayout_3.addWidget(self.guides_table)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.label = QtWidgets.QLabel(self.pdf_tab)
        self.label.setGeometry(QtCore.QRect(10, 60, 659, 17))
        self.label.setObjectName("label")
        self.ocr_pdf_btn = QtWidgets.QPushButton(self.pdf_tab)
        self.ocr_pdf_btn.setGeometry(QtCore.QRect(1000, 10, 141, 25))
        self.ocr_pdf_btn.setObjectName("ocr_pdf_btn")
        self.pdf_to_text_btn = QtWidgets.QPushButton(self.pdf_tab)
        self.pdf_to_text_btn.setGeometry(QtCore.QRect(10, 10, 171, 25))
        self.pdf_to_text_btn.setObjectName("pdf_to_text_btn")
        self.pdf_tab_3.addTab(self.pdf_tab, "")
        self.util_tab = QtWidgets.QWidget()
        self.util_tab.setObjectName("util_tab")
        self.build_db_btn = QtWidgets.QPushButton(self.util_tab)
        self.build_db_btn.setGeometry(QtCore.QRect(1000, 10, 141, 25))
        self.build_db_btn.setObjectName("build_db_btn")
        self.backup_db_btn = QtWidgets.QPushButton(self.util_tab)
        self.backup_db_btn.setGeometry(QtCore.QRect(10, 10, 141, 25))
        self.backup_db_btn.setObjectName("backup_db_btn")
        self.pdf_tab_3.addTab(self.util_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1166, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pdf_tab_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Traiter"))
        self.pdf_tab_3.setTabText(self.pdf_tab_3.indexOf(self.extract_tab), _translate("MainWindow", "Extract"))
        self.label.setText(_translate("MainWindow", "Extracted"))
        self.ocr_pdf_btn.setText(_translate("MainWindow", "OCR PDF"))
        self.pdf_to_text_btn.setText(_translate("MainWindow", "PDF to Text"))
        self.pdf_tab_3.setTabText(self.pdf_tab_3.indexOf(self.pdf_tab), _translate("MainWindow", "PDF"))
        self.build_db_btn.setText(_translate("MainWindow", "Build Database"))
        self.backup_db_btn.setText(_translate("MainWindow", "Backup Database"))
        self.pdf_tab_3.setTabText(self.pdf_tab_3.indexOf(self.util_tab), _translate("MainWindow", "Utilities"))
